"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Search, Zap, Flame, Droplets, Waves, Recycle, MapPin, ArrowUpRight, Building2, Copy, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import {geocode, lookup, type Candidate, type ServiceType, type UtilityResult} from "@/lib/utility-lookup";
const utilities=[{name:"Electricity",icon:Zap},{name:"Gas",icon:Flame},{name:"Water",icon:Droplets},{name:"Sewer",icon:Waves},{name:"Garbage / Recycling",icon:Recycle}];
const statusLabels={mapped:"Boundary match",review:"Needs verification",missing:"No match in source",error:"Source unavailable"};
type Report={property:Candidate;type:ServiceType;utilities:UtilityResult[]};
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
function mapUrl(c:Candidate){return `https://www.portlandmaps.com/?x=${c.x}&y=${c.y}&z=17`;}
export default function Home(){
 const [address,setAddress]=useState("");const type:ServiceType="residential";const [candidates,setCandidates]=useState<Candidate[]>([]);const [selected,setSelected]=useState<Candidate|null>(null);const [report,setReport]=useState<Report|null>(null);const [busy,setBusy]=useState("");const [error,setError]=useState("");const [copied,setCopied]=useState(false);const generation=useRef(0);
 const reset=()=>{generation.current++;setReport(null);setCandidates([]);setSelected(null);setError("");setBusy("");};
 const search=useCallback(async(value:string)=>{
  if(typeof value!=="string"||value.trim().length<6||value.length>250)throw new Error("Enter a street address, city, and state or ZIP.");
  const current=++generation.current;setAddress(value);setReport(null);setSelected(null);setCandidates([]);setError("");setBusy("Finding address matches…");
  try{const data={candidates:await geocode(value)};if(current!==generation.current)return [];setCandidates(data.candidates);if(!data.candidates.length)setError("No precise Oregon or Washington address matched. Add the street number, city, and ZIP code.");return data.candidates as Candidate[];}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:"Address search failed.");throw e;}finally{if(current===generation.current)setBusy("");}
 },[]);
 const runLookup=async(property:Candidate)=>{
  const current=++generation.current;setSelected(property);setReport(previous=>previous?.property.x===property.x&&previous?.property.y===property.y&&previous.type===type?previous:null);setCopied(false);setError("");setBusy("Checking utility maps…");
  try{const data={utilities:await lookup(property.x,property.y,type)};if(current===generation.current){setReport({property,type,utilities:data.utilities});setCandidates([]);}return data;}catch(e){if(current===generation.current)setError(e instanceof Error?e.message:"Lookup failed.");}finally{if(current===generation.current)setBusy("");}
 };
 useEffect(()=>{const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:"search_property_addresses",description:"Search Oregon and Washington street addresses and show candidates for the user to confirm before a utility lookup.",inputSchema:{type:"object",properties:{address:{type:"string",minLength:6,maxLength:250}},required:["address"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input!=="object"||!("address" in input)||typeof input.address!=="string")throw new Error("An address string is required.");return {candidates:await search(input.address)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[search]);
 const reportText=()=>report?`${report.property.address}\nProperty type: ${report.type}\n\n${report.utilities.map(r=>`${r.utility}: ${r.providers.map(p=>p.name).join(" / ")||"Not established"}\nStatus: ${statusLabels[r.status]}\n${r.note}\nSource: ${r.sourceUrl}\nChecked: ${r.checkedAt}`).join("\n\n")}`:"";
 const copy=async()=>{try{await navigator.clipboard.writeText(reportText());setCopied(true);}catch{setError("Copy was unavailable. Use Download CSV to save the report.");}};
 const download=()=>{if(!report)return;const cell=(value:string)=>`"${(/^[=+@\-\t\r]/.test(value)?"'":"")+value.replace(/"/g,'""')}"`;const rows=[["address","property_type","utility","provider","status","note","source","checked_at"],...report.utilities.map(r=>[report.property.address,report.type,r.utility,r.providers.map(p=>p.name).join(" / "),statusLabels[r.status],r.note,r.sourceUrl,r.checkedAt])];const url=URL.createObjectURL(new Blob(["\uFEFF"+rows.map(row=>row.map(cell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="property-utilities.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <main><header className="topbar"><div className="brand"><Building2 size={24}/><span>Property Utilities Lookup <span className="app-version">v g0.002</span></span></div><span className="region">Portland and surrounding communities · Coverage varies by utility</span></header><div className="workspace"><section className="search-panel">
 <form onSubmit={e=>{e.preventDefault();void search(address).catch(()=>{});}}><label htmlFor="address">Property address</label><div className="search-row"><MapPin size={21}/><Input id="address" value={address} onChange={e=>{reset();setAddress(e.target.value);}} placeholder="Street address, city, ZIP" required minLength={6} maxLength={250}/></div><Button disabled={!!busy} className="search-button" type="submit"><Search size={18}/>{busy?"Working…":"Find property"}</Button></form>
 <div aria-live="polite">{busy&&<p className="busy">{busy}</p>}{error&&<p role="alert" className="error">{error}</p>}{candidates.length>0&&!busy&&<div><h3 style={{marginTop:24}}>Confirm the property</h3><p style={{fontSize:14,color:"#54697b"}}>Choose the correct match. If addresses repeat, check the map location.</p>{candidates.map((c,i)=><div key={`${c.x}-${c.y}-${i}`}><button className="candidate" onClick={()=>void runLookup(c)}><strong>{c.address}</strong><span style={{display:"block",marginTop:6,color:"#54697b"}}>{c.matchType==="StreetAddress"?"Street estimate":"Address point"} · match score {Math.round(c.score)}<br/>{c.y.toFixed(5)}, {c.x.toFixed(5)} · Use this location</span></button><a style={{fontSize:13}} href={mapUrl(c)} target="_blank" rel="noopener noreferrer">Check location on PortlandMaps ↗</a></div>)}</div>}</div>
 </section>
 <section className="results-panel" aria-busy={!!busy}><div className="results-heading"><div><span className="section-label">Provider Report</span><h2>{report?.property.address||selected?.address||"Search a property to begin"}</h2></div><MapPin size={28}/></div><p className="helper">{report?`${report.type==="residential"?"House lookup":report.type==="multifamily"?"Multifamily / 5+ units":"Commercial"} · Checked ${new Date(report.utilities[0].checkedAt).toLocaleString()}`:"Confirm the matched address, then check each utility’s source and service area."}</p>
 {report&&<div className="actions"><Button variant="outline" onClick={()=>void copy()}><Copy size={16}/>{copied?"Copied":"Copy report"}</Button><Button variant="outline" onClick={download}><Download size={16}/>Download CSV</Button><Button variant="outline" onClick={()=>void runLookup(report.property)} disabled={!!busy}>Refresh</Button></div>}
 <div className="utility-list">{utilities.map(({name,icon:Icon},i)=>{const r=report?.utilities[i];return <article className="utility-row" key={name}><div className={`utility-icon icon-${i}`}><Icon size={23}/></div><div className="provider-body"><h3>{name}</h3>{r?<><span className={`badge ${r.status==="mapped"?"":r.status==="error"?"error":"review"}`}>{statusLabels[r.status]}</span><div className="provider-name">{r.providers.length?r.providers.map(p=>p.name).join(" / "):r.status==="review"?"Check the property’s contract":"Provider not established"}</div><p>{r.note}</p><div className="provider-links"><a href={r.sourceUrl} target="_blank" rel="noopener noreferrer">{r.source} ↗</a>{r.queryUrl&&<a href={r.queryUrl} target="_blank" rel="noopener noreferrer">View returned data ↗</a>}{r.providers.map((p,j)=><span key={j}>{p.phone&&<span>{p.phone} </span>}{p.website&&<a href={p.website} target="_blank" rel="noopener noreferrer">Provider website ↗</a>}</span>)}{name==="Sewer"&&<a href={mapUrl(report!.property)} target="_blank" rel="noopener noreferrer">Verify in PortlandMaps Utilities ↗</a>}{name==="Gas"&&<a href="https://www.nwnatural.com/account/start-stop-transfer" target="_blank" rel="noopener noreferrer">Confirm with NW Natural ↗</a>}</div></>:<p>{busy==="Checking utility maps…"?"Checking public sources…":"Awaiting property lookup"}</p>}</div>{!r&&<span className="empty-mark">—</span>}</article>;})}</div><div className="report-foot"><ArrowUpRight size={18}/><span>Mapped coverage identifies a potential provider. Building connections and private contracts may need confirmation. A missing result does not mean there is no service.</span></div></section></div></main>;
}






